// Name										code			msg
X(MSDB_ER_SUCCESS,							0,				"Success")
X(MSDB_ER_UNKNOWN_ERROR,					-1,				"Unknown error")
X(MSDB_ER_NOT_IMPLEMENTED,					1001,			"Not Implemented")
X(MSDB_ER_ALL_IO_ERROR,						2000,			"All IO error")
X(MSDB_ER_CANNOT_CREATE_FILE,				2001,			"Cannot create file")
X(MSDB_ER_CANNOT_OPEN_FILE,					2002,			"Cannot open file")
X(MSDB_ER_CANNOT_CREATE_DIR,				2011,			"Cannot create directory")
X(MSDB_ER_CANNOT_OPEN_DIR,					2012,			"Cannot open directory")
